ALLOW_ORIGINS: "*"

SERVER:
  PORT: 8081
  MODE: DEV
  LEVEL: INFO
  SERVICE_NAME: user
  ENVIRONMENT: local
  VERSION: 1.0

LOGGER:
  LOG_LEVEL: debug
  LOG_MAX_SIZE: 10
  LOG_MAX_AGE: 30
  LOG_MAX_BACKUPS: 5
  LOG_COMPRESS: true

CACHE:
  CACHE_HOST: localhost
  CACHE_PORT: 6380
  CACHE_USERNAME: 
  CACHE_PASSWORD: redisabc123

INTERNAL_URLS:
  USER_URL: http://localhost:8001
  SPORT_DATA_URL: http://localhost:8002
  NOTIFICATION_URL: http://localhost:8003

SQL:
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_DBNAME: user
  RDBMS: mysql
  MAX_CONN_IDLE_TIME: 5
  MAX_CONN_LIFE_TIME: 5
  MAX_CONNS: 10
  MAX_IDLE_CONNS: 2

ACCESS_TOKEN_SIGNING:
   PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIFicqPNjmI2M2XOLQC2jxuScDmUanu1YdP1pt0RBguva\n-----END PRIVATE KEY-----"
   ISSUER: "smm"
   EXPIRES_TIME: 86400

ID_TOKEN_SIGNING:
   PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIFicqPNjmI2M2XOLQC2jxuScDmUanu1YdP1pt0RBguva\n-----END PRIVATE KEY-----"
   ISSUER: "smm"
   EXPIRES_TIME: 86400

